version: '2'

services:
  faq:
    container_name: tetrika_test_app
    build: ./app
    volumes:
      - ./app/src:/usr/app
    restart: always
    ports:
      - 5000:5000
    env_file:
      - config.env
    depends_on:
      - tetrika_mysql


  tetrika_mysql:
    image: mysql:5.7
    env_file:
      - config.env
    ports:
      - 3310:3306
    networks:
      - default

networks:
  default:
